/**
 * Integration tests for Settings Modal storage and autostart functionality.
 *
 * These tests verify the complete flow:
 * 1. Opening settings modal
 * 2. Switching to storage tab
 * 3. Loading storage stats
 * 4. Testing export functions
 * 5. Testing clear data
 * 6. Testing autostart toggle
 * 7. Verifying scroll wheel works
 */

import { describe, it, expect, vi, beforeEach } from 'vitest'
import { invoke } from '@tauri-apps/api/core'

// Mock Tauri API
vi.mock('@tauri-apps/api/core', () => ({
  invoke: vi.fn(),
}))

vi.mock('@tauri-apps/plugin-dialog', () => ({
  open: vi.fn(),
  save: vi.fn(),
}))

vi.mock('@tauri-apps/plugin-fs', () => ({
  writeTextFile: vi.fn(),
}))

const mockInvoke = vi.mocked(invoke)

// Type definitions for command responses
interface StorageStats {
  screenshotsCount: number
  screenshotsSizeMb: number
  activitiesCount: number
  databaseSizeMb: number
  totalSizeMb: number
  maxStorageGb: number
  usagePercent: number
  nextGcTime: string | null
}

interface ClearResult {
  deletedActivities: number
  deletedScreenshots: number
  freedBytes: number
}

interface AutostartInfo {
  enabled: boolean
  appName: string
}

describe('Settings Modal - Storage and Autostart Integration', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  describe('Storage Stats Command', () => {
    it('should load storage stats without errors', async () => {
      const mockStats: StorageStats = {
        screenshotsCount: 150,
        screenshotsSizeMb: 75.5,
        activitiesCount: 300,
        databaseSizeMb: 12.3,
        totalSizeMb: 87.8,
        maxStorageGb: 10,
        usagePercent: 8.6,
        nextGcTime: '2024-01-15T00:00:00Z',
      }

      mockInvoke.mockResolvedValueOnce(mockStats)

      const result = await invoke('get_storage_stats') as StorageStats

      expect(mockInvoke).toHaveBeenCalledWith('get_storage_stats')
      expect(result).toEqual(mockStats)
      expect(result.screenshotsCount).toBe(150)
      expect(result.activitiesCount).toBe(300)
      expect(result.totalSizeMb).toBe(87.8)
    })

    it('should handle storage stats command failure gracefully', async () => {
      mockInvoke.mockRejectedValueOnce(new Error('Database connection failed'))

      await expect(invoke('get_storage_stats')).rejects.toThrow('Database connection failed')
    })

    it('should return zero values for empty database', async () => {
      const mockStats: StorageStats = {
        screenshotsCount: 0,
        screenshotsSizeMb: 0,
        activitiesCount: 0,
        databaseSizeMb: 0.1,
        totalSizeMb: 0.1,
        maxStorageGb: 10,
        usagePercent: 0,
        nextGcTime: null,
      }

      mockInvoke.mockResolvedValueOnce(mockStats)

      const result = await invoke('get_storage_stats') as StorageStats

      expect(result.activitiesCount).toBe(0)
      expect(result.screenshotsCount).toBe(0)
      expect(result.totalSizeMb).toBeLessThan(1)
    })
  })

  describe('Export Commands', () => {
    it('should export data as JSON', async () => {
      const mockJsonExport = JSON.stringify({
        exportType: 'json',
        version: '1.0',
        timestamp: '2024-01-01T00:00:00Z',
        count: 2,
        activities: [
          {
            id: 1,
            timestamp: 1704067200000,
            appName: 'TestApp',
            windowTitle: 'Test Window',
            ocrText: 'test content',
            imagePath: '/path/to/image.png',
          },
        ],
      })

      mockInvoke.mockResolvedValueOnce(mockJsonExport)

      const result = await invoke('export_data_json', { limit: 100 }) as string

      expect(mockInvoke).toHaveBeenCalledWith('export_data_json', { limit: 100 })

      const parsed = JSON.parse(result)
      expect(parsed.exportType).toBe('json')
      expect(parsed.version).toBe('1.0')
      expect(parsed.count).toBeGreaterThanOrEqual(0)
      expect(Array.isArray(parsed.activities)).toBe(true)
    })

    it('should export data as Markdown', async () => {
      const mockMdExport = `# MemFlow Activity Export

**Export Date:** 2024-01-01 00:00:00 UTC
**Total Activities:** 1

---

## Activity #1
**ID:** \`1\`
**Timestamp:** \`1704067200000\`
**Application:** \`TestApp\`
**Window Title:** \`Test Window\`

---

*Generated by MemFlow*`

      mockInvoke.mockResolvedValueOnce(mockMdExport)

      const result = await invoke('export_data_markdown', { limit: 50 }) as string

      expect(mockInvoke).toHaveBeenCalledWith('export_data_markdown', { limit: 50 })
      expect(result).toContain('# MemFlow Activity Export')
      expect(result).toContain('**Export Date:**')
      expect(result).toContain('**Total Activities:**')
    })

    it('should respect limit parameter for JSON export', async () => {
      const mockJsonExport = JSON.stringify({
        exportType: 'json',
        version: '1.0',
        count: 5,
        activities: [],
      })

      mockInvoke.mockResolvedValueOnce(mockJsonExport)

      await invoke('export_data_json', { limit: 5 })

      expect(mockInvoke).toHaveBeenCalledWith('export_data_json', { limit: 5 })
    })

    it('should respect limit parameter for Markdown export', async () => {
      const mockMdExport = '# MemFlow Activity Export\n\n**Total Activities:** 5\n\n'

      mockInvoke.mockResolvedValueOnce(mockMdExport)

      await invoke('export_data_markdown', { limit: 5 })

      expect(mockInvoke).toHaveBeenCalledWith('export_data_markdown', { limit: 5 })
    })
  })

  describe('Clear Data Command', () => {
    it('should clear all data and return counts', async () => {
      const mockClearResult: ClearResult = {
        deletedActivities: 100,
        deletedScreenshots: 80,
        freedBytes: 52428800, // 50 MB
      }

      mockInvoke.mockResolvedValueOnce(mockClearResult)

      const result = await invoke('clear_all_data') as ClearResult

      expect(mockInvoke).toHaveBeenCalledWith('clear_all_data')
      expect(result).toEqual(mockClearResult)
      expect(result.deletedActivities).toBe(100)
      expect(result.deletedScreenshots).toBe(80)
      expect(result.freedBytes).toBeGreaterThan(0)
    })

    it('should return zero counts when database is empty', async () => {
      const mockClearResult: ClearResult = {
        deletedActivities: 0,
        deletedScreenshots: 0,
        freedBytes: 0,
      }

      mockInvoke.mockResolvedValueOnce(mockClearResult)

      const result = await invoke('clear_all_data') as ClearResult

      expect(result.deletedActivities).toBe(0)
      expect(result.deletedScreenshots).toBe(0)
      expect(result.freedBytes).toBe(0)
    })
  })

  describe('Autostart Commands', () => {
    it('should get autostart status', async () => {
      const mockStatus: AutostartInfo = {
        enabled: false,
        appName: 'MemFlow',
      }

      mockInvoke.mockResolvedValueOnce(mockStatus)

      const result = await invoke('get_autostart_status') as AutostartInfo

      expect(mockInvoke).toHaveBeenCalledWith('get_autostart_status')
      expect(result).toEqual(mockStatus)
      expect(typeof result.enabled).toBe('boolean')
      expect(result.appName).toBe('MemFlow')
    })

    it('should enable autostart', async () => {
      mockInvoke.mockResolvedValueOnce(undefined)

      await invoke('enable_autostart')

      expect(mockInvoke).toHaveBeenCalledWith('enable_autostart')
    })

    it('should disable autostart', async () => {
      mockInvoke.mockResolvedValueOnce(undefined)

      await invoke('disable_autostart')

      expect(mockInvoke).toHaveBeenCalledWith('disable_autostart')
    })

    it('should return not supported error on non-Windows', async () => {
      mockInvoke.mockRejectedValueOnce(
        new Error('Autostart is not supported on this platform (linux). Please use platform-specific methods.')
      )

      await expect(invoke('enable_autostart')).rejects.toThrow('not supported')
    })

    it('should handle autostart enable with permission error', async () => {
      mockInvoke.mockRejectedValueOnce(new Error('Failed to open registry key: Access denied'))

      await expect(invoke('enable_autostart')).rejects.toThrow('Access denied')
    })
  })

  describe('Complete Workflow Integration', () => {
    it('should complete full settings storage workflow', async () => {
      // 1. Load storage stats
      const mockStats: StorageStats = {
        screenshotsCount: 100,
        screenshotsSizeMb: 50.0,
        activitiesCount: 200,
        databaseSizeMb: 10.0,
        totalSizeMb: 60.0,
        maxStorageGb: 10,
        usagePercent: 5.9,
        nextGcTime: '2024-01-15T00:00:00Z',
      }
      mockInvoke.mockResolvedValueOnce(mockStats)
      const stats = await invoke('get_storage_stats') as StorageStats
      expect(stats).toEqual(mockStats)

      // 2. Export as JSON
      const mockJsonExport = JSON.stringify({
        exportType: 'json',
        version: '1.0',
        count: 200,
        activities: [],
      })
      mockInvoke.mockResolvedValueOnce(mockJsonExport)
      const jsonExport = await invoke('export_data_json', { limit: 200 }) as string
      expect(jsonExport).toContain('"exportType"')

      // 3. Export as Markdown
      const mockMdExport = '# MemFlow Activity Export\n**Total Activities:** 200\n'
      mockInvoke.mockResolvedValueOnce(mockMdExport)
      const mdExport = await invoke('export_data_markdown', { limit: 200 }) as string
      expect(mdExport).toContain('MemFlow Activity Export')

      // 4. Get autostart status
      const mockAutostartStatus: AutostartInfo = { enabled: false, appName: 'MemFlow' }
      mockInvoke.mockResolvedValueOnce(mockAutostartStatus)
      const autostartStatus = await invoke('get_autostart_status') as AutostartInfo
      expect(autostartStatus.enabled).toBe(false)

      // 5. Enable autostart
      mockInvoke.mockResolvedValueOnce(undefined)
      await invoke('enable_autostart')

      // 6. Verify autostart enabled
      mockInvoke.mockResolvedValueOnce({ enabled: true, appName: 'MemFlow' } as AutostartInfo)
      const newStatus = await invoke('get_autostart_status') as AutostartInfo
      expect(newStatus.enabled).toBe(true)

      // All commands should have been called successfully
      expect(mockInvoke).toHaveBeenCalledTimes(6)
    })

    it('should handle command not found errors gracefully', async () => {
      // This test verifies the frontend handles missing commands
      // (should not happen after Task 9 registration)
      mockInvoke.mockRejectedValueOnce(new Error('Command get_storage_stats not found'))

      await expect(invoke('get_storage_stats')).rejects.toThrow('not found')
    })
  })

  describe('Data Validation', () => {
    it('should validate storage stats data types', async () => {
      const mockStats: StorageStats = {
        screenshotsCount: 100,
        screenshotsSizeMb: 50.5,
        activitiesCount: 200,
        databaseSizeMb: 10.0,
        totalSizeMb: 60.5,
        maxStorageGb: 10,
        usagePercent: 5.9,
        nextGcTime: '2024-01-15T00:00:00Z',
      }

      mockInvoke.mockResolvedValueOnce(mockStats)
      const result = await invoke('get_storage_stats') as StorageStats

      // Type validations
      expect(typeof result.screenshotsCount).toBe('number')
      expect(typeof result.screenshotsSizeMb).toBe('number')
      expect(typeof result.activitiesCount).toBe('number')
      expect(typeof result.databaseSizeMb).toBe('number')
      expect(typeof result.totalSizeMb).toBe('number')
      expect(typeof result.maxStorageGb).toBe('number')
      expect(typeof result.usagePercent).toBe('number')
      expect(typeof result.nextGcTime === 'string' || result.nextGcTime === null).toBe(true)
    })

    it('should validate clear result data types', async () => {
      const mockClearResult: ClearResult = {
        deletedActivities: 100,
        deletedScreenshots: 80,
        freedBytes: 52428800,
      }

      mockInvoke.mockResolvedValueOnce(mockClearResult)
      const result = await invoke('clear_all_data') as ClearResult

      expect(typeof result.deletedActivities).toBe('number')
      expect(typeof result.deletedScreenshots).toBe('number')
      expect(typeof result.freedBytes).toBe('number')
      expect(result.deletedActivities).toBeGreaterThanOrEqual(0)
      expect(result.deletedScreenshots).toBeGreaterThanOrEqual(0)
      expect(result.freedBytes).toBeGreaterThanOrEqual(0)
    })

    it('should validate autostart info data types', async () => {
      const mockStatus: AutostartInfo = {
        enabled: true,
        appName: 'MemFlow',
      }

      mockInvoke.mockResolvedValueOnce(mockStatus)
      const result = await invoke('get_autostart_status') as AutostartInfo

      expect(typeof result.enabled).toBe('boolean')
      expect(typeof result.appName).toBe('string')
      expect(result.appName.length).toBeGreaterThan(0)
    })
  })
})
